name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add this permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      - name: Build
        run: npm run build
        env:
          BASE_PATH: /resources/ # Make sure this is your repo name

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: dist
